sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t msultakov/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true msultakov/udemy-docker-react npm run test
