sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t msultakov/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true msultakov/udemy-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "udemy-docker-react"
  env: "UdemyDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-328045133942"
  bucket_paht: "udemy-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
